---
# tasks file for samba

- name: "fail if Operating System is not CentOS-7.x"
  fail: msg="Operating System {{ ansible_distribution }}-{{ ansible_distribution_version }} not supported"
  when: ansible_distribution != "CentOS" or ansible_distribution_major_version != "7"

- name: install samba on CentOS
  include: centos.yml
